services:
  - type: web
    name: worldastical
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: FLASK_DEBUG
        value: false
      - key: SESSION_COOKIE_SECURE
        value: true
