# -------------
# App Configuration
# -------------

# Theme
[theme]
base="light"

[ui]
hideTopBar = true


# App behavior
[server]
headless = true
enableCORS = true
port = 8501

[browser]
gatherUsageStats = false